<?php print_r($block->getCatIcon());        

?>
<div class="categories-img mt-n4 mt-lg-0 pr-lg-2 order-2">
<div class="row category-list m-auto thin-gutters justify-content-between container">
<?php
foreach ($block->getCatIcon() as $value) {
   ?>
   <div class="col-3 py-2 col-lg text-center">
                <a href="https://www.sono.no/produkter/kontorutstyr.aspx" class="d-block category-icon-container text-warning-hover">
        <img src=<?php $value ?> class="img-fluid" data-pagespeed-url-hash="3305479001" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
        <span class="font-family-verdana-pro-cond font-weight-semibold">Kontorutstyr</span>
    </a>
        </div>

        <?php
}
?>

<div class="categories-img mt-n4 mt-lg-0 pr-lg-2 order-2">
    <div class="row category-list m-auto thin-gutters justify-content-between container">
        <div class="col-3 py-2 px-0 col-lg text-center">
            <a href="" class="d-block icon-text">
                <img alt="" class="img-fluid" src="http://sonolayout.web80.hostingpool.net/pub/static/version1597680974/frontend/Ereactor/sono/nb_NO/images/icons/Kontormobler-icon.svg">
                <span>Kontormøbler</span>
            </a>
        </div>
        <div class="col-3 py-2  px-0 col-lg text-center">
            <a href="" class="d-block icon-text">
                <img alt="" class="img-fluid" src="http://sonolayout.web80.hostingpool.net/pub/static/version1597680974/frontend/Ereactor/sono/nb_NO/images/icons/Kontorutstyr-icon.svg">
                <span>Kontorutstyr</span>
            </a>
        </div>
        <div class="col-3 py-2 px-0 col-lg text-center">
            <a href="" class="d-block icon-text">
                <img alt="" class="img-fluid" src="http://sonolayout.web80.hostingpool.net/pub/static/version1597680974/frontend/Ereactor/sono/nb_NO/images/icons/Lager-icon.svg">
                <span>Lager</span>
            </a>
        </div>
        <div class="col-3 py-2 px-0 col-lg text-center">
            <a href="" class="d-block icon-text">
                <img alt="" class="img-fluid" src="http://sonolayout.web80.hostingpool.net/pub/static/version1597680974/frontend/Ereactor/sono/nb_NO/images/icons/Verksted-icon.svg">
                <span>Verksted</span>
            </a>
        </div>
        <div class="col-3 py-2 px-0 col-lg text-center">
            <a href="" class="d-block icon-text">
                <img alt="" class="img-fluid" src="http://sonolayout.web80.hostingpool.net/pub/static/version1597680974/frontend/Ereactor/sono/nb_NO/images/icons/Garderobe-icon.svg">
                <span>Garderobe</span>
            </a>
        </div>
        <div class="col-3 py-2 px-0 col-lg text-center">
            <a href="" class="d-block icon-text">
                <img alt="" class="img-fluid" src="http://sonolayout.web80.hostingpool.net/pub/static/version1597680974/frontend/Ereactor/sono/nb_NO/images/icons/Stalskap-icon.svg">
                <span>Stålskap</span>
            </a>
        </div>
        <div class="col-3 py-2 px-0 col-lg text-center">
            <a href="" class="d-block icon-text">
                <img alt="" class="img-fluid" src="http://sonolayout.web80.hostingpool.net/pub/static/version1597680974/frontend/Ereactor/sono/nb_NO/images/icons/Skole-og-Barnehage-icon.svg">
                <span>Skole og Barnehage</span>
            </a>
        </div>
        <div class="col-3 py-2 px-0 col-lg text-center">
            <a href="" class="d-block icon-text">
                <img alt="" class="img-fluid" src="http://sonolayout.web80.hostingpool.net/pub/static/version1597680974/frontend/Ereactor/sono/nb_NO/images/icons/Omgivelser-og-HMS-icon.svg">
                <span>Omgivelser og HMS</span>
            </a>
        </div>
    </div>

    <div class="mobile-chat d-block d-sm-none w-100 child-p-mb-0 font-size-14 font-weight-semibold text-center mt-2 py-3">
        <p>Alltid fornøyd</p>
        <div>&nbsp;</div>
        <p>Gratis frakt t.o.m. 31. mars 2020</p>
        <div>&nbsp;</div>
        <p>24 timers levering til kontor, lager og industri</p>
    </div>
</div>