<?php print_r($block->getCatIcon()); 
foreach ($block->getCatIcon() as $value) {
   ?>
   <div class="col-3 py-2 col-lg text-center">
                <a href="https://www.sono.no/produkter/kontorutstyr.aspx" class="d-block category-icon-container text-warning-hover">
        <img src=<?php $value ?> class="img-fluid" data-pagespeed-url-hash="3305479001" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">
        <span class="font-family-verdana-pro-cond font-weight-semibold">Kontorutstyr</span>
    </a>
        </div>

        <?php
}
?>