
<div class="categories-img mt-n4 mt-lg-0 pr-lg-2 order-2">
<div class="row category-list m-auto thin-gutters justify-content-between container">
<?php
    $categories = $this->getCategoryCollection();
    $categoryHelper = $this->getCategoryHelper();


foreach($categories as $category):
    $cat = $this->getCategorymodel($category->getId());
    $image = $cat->getImageUrl();
    echo print_r($image);
?>
    <?php if($image != null): ?>
        <div class="col-md-4">
            <a class="category_name" href="<?php echo $cat->getUrl(); ?>">
               <img src="<?php echo $image; ?>" class="img-responsive category_image" alt="<?php echo $cat->getName(); ?>" />
                <h3><span><?php echo $cat->getName(); ?></span></h3>
            </a>
        </div>
    <?php endif; ?>
<?php endforeach; ?>

</div>
</div>
