
<div class="categories-img mt-n4 mt-lg-0 pr-lg-2 order-2">
<div class="row category-list m-auto thin-gutters justify-content-between container">
<?php

$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Ereactor\CategoryIconmodule\Block\Widget\testcat');
 

// print current product data
if ($currentProduct = $myBlock->getCurrentProduct()) {
    echo $currentProduct->getName() . '<br />';
    echo $currentProduct->getSku() . '<br />';
    echo $currentProduct->getFinalPrice() . '<br />';
    echo $currentProduct->getProductUrl() . '<br />';
    print_r ($currentProduct->getCategoryIds()) . '<br />';    
}
$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Ereactor\CategoryIconmodule\Block\Widget\testcat');
echo "test";
// print current category data
if ($currentCategory = $myBlock->getCurrentCategory()) {    
    echo $currentCategory->getName() . '<br />';
    echo $currentCategory->getUrl() . '<br />';        
}
foreach ($block->getCatIcon() as $value) {
     echo print_r($value);
?>
      <div class="row category-list m-auto thin-gutters justify-content-between container">
      <div class="col-3 py-2 px-0 col-lg text-center">
          <a href="<?php echo $value["url"] ?>" class="d-block icon-text">
              <img alt="" class="img-fluid" src="<?php echo $value["img"] ?>">
              <span><?php echo $value["name"]?></span>
          </a>
      </div>
      </div>
      
        <?php 
}
?>
</div>
</div>